### ISSUE TITLE
Getting an Error

### ISSUE THREAD

**Issue by AlexBarbulescu** [yuta0801/youtube-live-chat#2]
I'm getting this error when I try to run the script demo.

> ready!
> /var/www/node_modules/youtube-live-chat/index.js:94
>       for (const item of data.items) {
>                              ^
> 
> TypeError: Cannot read property 'items' of undefined
>     at Timeout.interval.setInterval [as _repeat] (/var/www/node_modules/youtube-live-chat/index.js:94:30)
>     at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
>     at tryOnTimeout (timers.js:232:11)
>     at Timer.listOnTimeout (timers.js:202:5)

**Comment by officiallyemma** [comment]
haha a bit late on this one but try https://github.com/Hennamann/youtube-live-chat

its the same thing but it actually works!

**Comment by yuta0801** [comment]
I don't know why that occurring, but I prevented errors from occurring temporarily.

**Comment by officiallyemma** [comment]
I actually ended up adding a few features to my own fork https://github.com/qwazwsx/youtube-live-chat

namely, a call for after all chats are parsed and the ability to input a video ID instead of a channel ID

**Comment by whopiyush** [comment]
Any Updates On This?

**Comment by yuta0801** [comment]
Sorry for my long silence.
I found a serious bug when I confirmed it now, and I'll fix it soon

**Comment by yuta0801** [comment]
fixed by 1.0.2

**Comment by whopiyush** [comment]
Thnks
